version: "2.4"
services:
  postgres_test:
    container_name: "{{cookiecutter.project_slug}}-postgres-test"
    # network_mode: host
    image: "postgres:{{cookiecutter.postgresql_version}}"
    env_file:
      - .env.test
    ports:
      - "54321:5432"
